(define (square x) (* x x))
(define (sum-of-squares x y) (+ (square x) (square y)))
(define (sum-of-largest-square x y z)
        (cond ((> x y) (if (> y z) (sum-of-squares x y) (sum-of-squares x z)))
              ((> y x) (if (> x z) (sum-of-squares y x) (sum-of-squares y z)))))
